services:
  prompt-optimizer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prompt-optimizer
    restart: unless-stopped
    ports:
      - "8999:80"
    environment:
      - NGINX_PORT=80
      - MCP_HTTP_PORT=3047
    security_opt:
      - no-new-privileges:true
