version: '3.8'

services:
  prompt-optimizer:
    build:
      context: .
      dockerfile: Dockerfile.cn
    container_name: prompt-optimizer
    restart: unless-stopped
    ports:
      - "8999:80"
    environment:
      - NGINX_PORT=80
      - MCP_HTTP_PORT=3047
    image: registry.cn-hangzhou.aliyuncs.com/your-namespace/prompt-optimizer:latest
    security_opt:
      - no-new-privileges:true